payment_method.settings.lunar:
  mapping:
    app_key:
      type: string
      label: 'Private API key'
    public_key:
      type: string
      label: 'Public API key'
    logo_url:
      type: string
      label: 'Logo URL'
    description:
      type: text
      label: 'Payment method description'
    shop_title:
      type: string
      label: 'Shop title'
payment_method.settings.lunarmobilepay:
  mapping:
    app_key:
      type: string
      label: 'Private API key'
    public_key:
      type: string
      label: 'Public API key'
    configuration_id:
      type: string
      label: 'Configuration ID'
    logo_url:
      type: string
      label: 'Logo URL'
    description:
      type: text
      label: 'Payment method description'
    shop_title:
      type: string
      label: 'Shop title'
